#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then 
	echo "run as root, e.g. 'sudo $0 <user> <server url>'"
	exit 1
fi

if [ -z "$1" ]; then
	echo "no user provided, run again like this: '$0 <user> <server url>'"
	exit 1
fi

if [ -z "$2" ]; then
	echo "no server provided, run again like this: '$0 <user> <server url>'"
	exit 1
fi

which systemctl > /dev/null 2>&1 && \
	systemctl start "$(systemd-escape --template=secprac-client@.service "$1 $2")" > /dev/null 2>&1 && \
	echo "started secprac-client service successfully (you may close this terminal)" && exit

echo "failed to start systemd service, running secprac-client directly"
echo ""
echo "      WARNING: DO NOT CLOSE THIS TERMINAL      "
echo ""

/usr/local/bin/secprac-client "$1" "$2"
